name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12
      - uses: SonarSource/ci-github-actions/build-maven@v1 # dogfood
        with:
          maven-args: -Dcommercial -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/report-aggregate/target/site/jacoco-aggregate/jacoco.xml
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          scanner-java-opts: '-Xmx2g'
      - name: Run IRIS sync
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.core:sonarlint-core-parent"
          shadow2_platform: "SQC-US"
